// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUZ-tK15hpr-sMx9IZ0iBS6B6cw0foMe0',
    appId: '1:607325887465:web:b9e1148df731df700fc978',
    messagingSenderId: '607325887465',
    projectId: 'shopflutter-ecc80',
    authDomain: 'shopflutter-ecc80.firebaseapp.com',
    storageBucket: 'shopflutter-ecc80.appspot.com',
    measurementId: 'G-31N98PYCB5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0yCJhDKUQ9LizOuNtmwU2ZA410K_M-2Q',
    appId: '1:607325887465:android:e1c7056a1751be820fc978',
    messagingSenderId: '607325887465',
    projectId: 'shopflutter-ecc80',
    storageBucket: 'shopflutter-ecc80.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8gGpHH1IdjiqjtDmSzOhYV6s3UkI2zjM',
    appId: '1:607325887465:ios:4d372601485c3d5c0fc978',
    messagingSenderId: '607325887465',
    projectId: 'shopflutter-ecc80',
    storageBucket: 'shopflutter-ecc80.appspot.com',
    iosBundleId: 'com.example.shopFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8gGpHH1IdjiqjtDmSzOhYV6s3UkI2zjM',
    appId: '1:607325887465:ios:5218e57dcd5846560fc978',
    messagingSenderId: '607325887465',
    projectId: 'shopflutter-ecc80',
    storageBucket: 'shopflutter-ecc80.appspot.com',
    iosBundleId: 'com.example.shopFlutter.RunnerTests',
  );
}
