// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZ4hpCkFOMblWuZpaiJpTzMOfOloWFbMc',
    appId: '1:493699491396:web:d1fad5fb4cd4c6716c7e11',
    messagingSenderId: '493699491396',
    projectId: 'fluttershop-e8298',
    authDomain: 'fluttershop-e8298.firebaseapp.com',
    storageBucket: 'fluttershop-e8298.appspot.com',
    measurementId: 'G-D9D6S5PJTT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBq8iJD6lZpwKQiVhyKd-5W78QPYIcDwZc',
    appId: '1:493699491396:android:5d322335e3756f7b6c7e11',
    messagingSenderId: '493699491396',
    projectId: 'fluttershop-e8298',
    storageBucket: 'fluttershop-e8298.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPHHo6Fgq4CMZ9qJRBV3zMfHUe4Ouzxec',
    appId: '1:493699491396:ios:89c857eda72639076c7e11',
    messagingSenderId: '493699491396',
    projectId: 'fluttershop-e8298',
    storageBucket: 'fluttershop-e8298.appspot.com',
    iosBundleId: 'com.example.shopFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPHHo6Fgq4CMZ9qJRBV3zMfHUe4Ouzxec',
    appId: '1:493699491396:ios:f19d3a99e856191a6c7e11',
    messagingSenderId: '493699491396',
    projectId: 'fluttershop-e8298',
    storageBucket: 'fluttershop-e8298.appspot.com',
    iosBundleId: 'com.example.shopFlutter.RunnerTests',
  );
}
